language: python
python:
  - "3.5.3"

install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install coverage
  - pip install nose

services:
  - postgresql

before_script:
  - psql -c "create database trackerdb;" -U postgres

script: 
  - nosetests --with-coverage
  
after_success:
  - coveralls
